### ISSUE TITLE
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by mengyaaa** [GuangmingZhu/AttentionConvLSTM#6]
hello, this is the error I encountered, hope to get any help,thank you~
Traceback (most recent call last):
  File "training_res3d_clstm_mobilenet.py", line 96, in <module>
    feature = res3d_clstm_mobilenet(inputs, seq_len, weight_decay)
  File "./networks/res3d_clstm_mobilenet.py", line 199, in res3d_clstm_mobilenet
    features = keras.layers.Reshape((seq_len/2,4,4,1024), name='feature_reshape')(features)
  File "/home/lab226/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/engine/topology.py", line 396, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/home/lab226/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/lab226/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/layers/core.py", line 402, in call
    return K.reshape(inputs, (-1,) + tuple(target_shape))
  File "/home/lab226/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/backend.py", line 1892, in reshape
    return array_ops.reshape(x, shape)
  File "/home/lab226/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in reshape
    name=name)
  File "/home/lab226/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 589, in apply_op
    param_name=input_name)
  File "/home/lab226/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

**Comment by GuangmingZhu** [comment]
@mengyaaa The seq_len should be even.

**Comment by jdlyw** [comment]
@GuangmingZhu 我也遇到了这个问题，而且seq_len没有改过，是源代码中的32，不知道为什么，还是报了这个错误

**Comment by mhasani1373** [comment]
hello, 
I have same problem, in my case the seq_len is 32 (even number)
((nb_epoch: 10 - seq_len: 32 - batch_size: 2 - weight_decay: 0.000050))

i use TF1.2 and keras 2.2.4,
 thank you

**Comment by yzf123456** [comment]
hello,
I also encountered the same problem, can you explain how to modify it?Thank you.

**Comment by yzf123456** [comment]
hello,
I also encountered the same problem, can you explain how to modify it?Thank you.
@GuangmingZhu

**Comment by migedan** [comment]
I also encountered the same problem, can you explain how to modify it?
